Improve error handling

diff --git a/.github/workflows/publish-manuscript.yaml b/.github/workflows/publish-manuscript.yaml
--- a/.github/workflows/publish-manuscript.yaml
+++ b/.github/workflows/publish-manuscript.yaml
@@ -57,9 +57,10 @@ jobs:
             --msa "${{ github.event.inputs.msa }}" | \
             tee manuscripts-new.json > /dev/null
           # check the exit status of all commands in the pipeline
-          for status in "${PIPESTATUS[@]}"; do
-            if [ "$status" -ne 0 ]; then
-              echo "A command in the pipeline failed"
+          status=("${PIPESTATUS[@]}")
+          for i in "${!status[@]}"; do
+            if [ "${status[$i]}" -ne 0 ]; then
+              echo "Pipeline step $i failed with status ${status[$i]}"
               exit 1
             fi
           done
